SQLALCHEMY_TRACK_MODIFICATIONS = False

### Environment-specific ###

# Flask
SECRET_KEY = ''
DEBUG = False

# Database
SQLALCHEMY_DATABASE_URI = ''

# Mail
MAIL_SERVER = ''
MAIL_PORT = 25
MAIL_USE_TLS = True
MAIL_USERNAME = None
MAIL_PASSWORD = None
MAIL_DEFAULT_SENDER = None
MAIL_MAX_EMAILS = None
